name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install minimal stable with rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libavutil-dev libavformat-dev libavcodec-dev libswscale-dev libavdevice-dev libavfilter-dev ffmpeg
      - name: Install minimal stable with clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libavutil-dev libavformat-dev libavcodec-dev libswscale-dev libavdevice-dev libavfilter-dev ffmpeg
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo test
        run: cargo test --verbose

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libavutil-dev libavformat-dev libavcodec-dev libswscale-dev libavdevice-dev libavfilter-dev ffmpeg
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Generate coverage report
        run: cargo tarpaulin --out Html --output-dir coverage-report
      - name: Upload coverage report
        uses: actions/upload-artifact@v4.4.3
        with:
          name: coverage-report
          path: coverage-report/tarpaulin-report.html
